Use LZMA compression
XZ compression breaks the build:

Error: inflate failed [invalid block type] at file offset [1988778]
imgdiff only supports gzip kernel compression,
did you try CONFIG_KERNEL_LZO?
failed to break apart source image
make: *** [out/target/product/flo/obj/PACKAGING/
recovery_patch_intermediates/recovery_from_boot.p] Error 1

Switching to LZMA compression eliminates this error and it builds
and runs just fine.

Change-Id: I694a4ad04d11704a43fa269f45ce7d0c6158ff70